name: Deploy Firebase Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd functions
        npm install
        
    - name: Create .env file
      run: |
        cd functions
        echo "GMAIL_USER=${{ secrets.GMAIL_USER }}" >> .env
        echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> .env
        
    - name: Setup Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Deploy to Firebase
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json
        firebase deploy --only functions --project kyuyoprint
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}